ALTER TABLE `tendoo_nexo_rayons` CHANGE `DESCRIPTION` `DESCRIPTION` TEXT NOT NULL; -- modifie la structure de la table rayons --

ALTER TABLE `tendoo_nexo_fournisseurs` ADD `DESCRIPTION` TEXT NOT NULL AFTER `AUTHOR`; -- ajoute un champ description pour le rayons --

ALTER TABLE `tendoo_Nexo_arrivages` CHANGE `DESCRIPTION` `DESCRIPTION` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
 -- ' modification de la colonne Description --
 
 -- Modification de la table Produit --
 
 ALTER TABLE `tendoo_nexo_articles` ADD `POIDS` VARCHAR(200) NOT NULL AFTER `AUTHOR`, ADD `REF_CODE` INT NOT NULL AFTER `POIDS`, ADD `REF_RAYON` INT NOT NULL AFTER `REF_CODE`, ADD `REF_SHIPPING` INT NOT NULL AFTER `REF_RAYON`, ADD `QUANTITY` INT NOT NULL AFTER `REF_SHIPPING`, ADD `DEFECTUEUX` INT NOT NULL AFTER `QUANTITY`, ADD `FRAIS_ACCESSOIRE` INT NOT NULL AFTER `DEFECTUEUX`, ADD `TAUX_DE_MARGE` INT NOT NULL AFTER `FRAIS_ACCESSOIRE`, ADD `HAUTEUR` VARCHAR(200) NOT NULL AFTER `TAUX_DE_MARGE`, ADD `LARGEUR` VARCHAR(200) NOT NULL AFTER `HAUTEUR`;
 
 -- Modification table produit -- 
 ALTER TABLE `tendoo_nexo_articles` ADD `ACTIVER_PROMOTION` BOOLEAN NOT NULL AFTER `TYPE`, ADD `DEBUT_PROMOTION` DATETIME NOT NULL AFTER `ACTIVER_PROMOTION`, ADD `FIN_PROMOTION` DATETIME NOT NULL AFTER `DEBUT_PROMOTION`;
 
 ALTER TABLE `tendoo_nexo_articles` ADD `DESCRIPTION` TEXT NOT NULL AFTER `FIN_PROMOTION`;
 
 ALTER TABLE `tendoo_nexo_articles` ADD `APERCU` VARCHAR(200) NOT NULL AFTER `DESCRIPTION`;
 
 ALTER TABLE `tendoo_nexo_articles` ADD `PRIX_DACHAT` INT NOT NULL AFTER `APERCU`;
 
 ALTER TABLE `tendoo_nexo_articles` ADD `CODEBAR` INT NOT NULL AFTER `PRIX_DACHAT`;
